GET  http://localhost:3000/tasks

### 
GET http://localhost:3000/tasks/0d378544-8971-4f18-8f5e-ca7c30b81965


### 
POST http://localhost:3000/tasks
Content-Type: application/json

{
  "name": "Colab 01",
  "description": "Spring 03"
}

### 
POST http://localhost:3000/tasks/a58273bf-aa83-4566-800c-c5cc80d14aa9/start
Content-Type: application/json

{
  "start_at": "2024-07-20"
}



###
PATCH  http://localhost:3000/tasks/a16d913b-3e59-457b-889f-ce225546942c
Content-Type: application/json

{
  "name": "Colab 11",
  "description": "Spring 032",
  "start_at": "2024-07-12"
}